CREATE TABLE albums (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    jellyfin_id VARCHAR(255) NOT NULL,
    title VARCHAR NOT NULL,
    artist VARCHAR NOT NULL,
    downloaded BOOLEAN NOT NULL DEFAULT FALSE
)
